#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.elf.MSP430{1,0,4.4,5
#
msp430g2x33_adc10_temp_sens.xe430: package/cfg/msp430g2x33_adc10_temp_sens.xe430.mak

clean::
	-$(RM) package/cfg/msp430g2x33_adc10_temp_sens.xe430.mak
